// Package event provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package event

import (
	externalRef0 "github.com/meshery/schemas/models/v1alpha1/core"
)

// BulkDeleteRequest defines model for BulkDeleteRequest.
type BulkDeleteRequest struct {
	Ids []externalRef0.Uuid `json:"ids" yaml:"ids"`
}

// BulkUpdateStatusRequest defines model for BulkUpdateStatusRequest.
type BulkUpdateStatusRequest struct {
	Ids    []externalRef0.Uuid `json:"ids" yaml:"ids"`
	Status string              `json:"status" yaml:"status"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty" yaml:"error,omitempty"`
}

// UpdateEventStatusRequest defines model for UpdateEventStatusRequest.
type UpdateEventStatusRequest struct {
	Status string `json:"status" yaml:"status"`
}
