// Package key provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package key

import (
	externalRef0 "github.com/meshery/schemas/models/v1alpha1/core"
)

// Key Represents an authorization key used for access control.
type Key struct {
	// Id A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	Id externalRef0.Uuid `json:"id" yaml:"id"`

	// Owner A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	Owner externalRef0.Uuid `json:"owner" yaml:"owner"`

	// Function Operation permitted by the key.
	Function string `db:"function" json:"function" yaml:"function"`

	// Category Category for the key.
	Category string `db:"category" json:"category" yaml:"category"`

	// Subcategory Subcategory for the key.
	Subcategory string `db:"subcategory" json:"subcategory" yaml:"subcategory"`

	// Description Human readable description of the key.
	Description string `db:"description" json:"description" yaml:"description"`

	// CreatedAt Timestamp when the resource was created.
	CreatedAt externalRef0.CreatedAt `db:"created_at" json:"created_at" yaml:"created_at"`

	// UpdatedAt Timestamp when the resource was updated.
	UpdatedAt externalRef0.UpdatedAt `db:"updated_at" json:"updated_at" yaml:"updated_at"`

	// DeletedAt SQL null Timestamp to handle null values of time.
	DeletedAt externalRef0.NullTime `json:"deleted_at,omitempty" yaml:"deleted_at,omitempty"`
}

// KeyPage defines model for KeyPage.
type KeyPage struct {
	Page       externalRef0.Number `json:"page" yaml:"page"`
	PageSize   externalRef0.Number `json:"page_size" yaml:"page_size"`
	TotalCount externalRef0.Number `json:"total_count" yaml:"total_count"`
	Keys       []struct {
		// Id A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
		Id externalRef0.Uuid `json:"id" yaml:"id"`

		// Owner A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
		Owner externalRef0.Uuid `json:"owner" yaml:"owner"`

		// Function Operation permitted by the key.
		Function string `db:"function" json:"function" yaml:"function"`

		// Category Category for the key.
		Category string `db:"category" json:"category" yaml:"category"`

		// Subcategory Subcategory for the key.
		Subcategory string `db:"subcategory" json:"subcategory" yaml:"subcategory"`

		// Description Human readable description of the key.
		Description string `db:"description" json:"description" yaml:"description"`

		// CreatedAt Timestamp when the resource was created.
		CreatedAt externalRef0.CreatedAt `db:"created_at" json:"created_at" yaml:"created_at"`

		// UpdatedAt Timestamp when the resource was updated.
		UpdatedAt externalRef0.UpdatedAt `db:"updated_at" json:"updated_at" yaml:"updated_at"`

		// DeletedAt SQL null Timestamp to handle null values of time.
		DeletedAt externalRef0.NullTime `json:"deleted_at,omitempty" yaml:"deleted_at,omitempty"`
	} `json:"keys" yaml:"keys"`
}

// KeyPayload Payload for creating or updating a key.
type KeyPayload struct {
	// Id A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	Id *externalRef0.Uuid `json:"id,omitempty" yaml:"id,omitempty"`

	// Function Operation permitted by the key.
	Function *string `json:"function,omitempty" yaml:"function,omitempty"`

	// Category Category for the key.
	Category *string `json:"category,omitempty" yaml:"category,omitempty"`

	// Subcategory Subcategory for the key.
	Subcategory *string `json:"subcategory,omitempty" yaml:"subcategory,omitempty"`

	// Description Human readable description of the key.
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`
}

// KeyId A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
type KeyId = externalRef0.Uuid

// ExternalRef0Order defines model for order.
type ExternalRef0Order = string

// OrgID A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
type OrgID = externalRef0.Uuid

// ExternalRef0Page defines model for page.
type ExternalRef0Page = string

// ExternalRef0Pagesize defines model for pagesize.
type ExternalRef0Pagesize = string

// ExternalRef0Search defines model for search.
type ExternalRef0Search = string
