// Package team provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package team

import (
	"github.com/meshery/schemas/models/core"
	externalRef0 "github.com/meshery/schemas/models/v1alpha1/core"
)

// Team A Team is a group of one or more users. Teams are often used as a grouping mechanism for assigning permissions, whether in the context of an organization, a workspace, or some other domain within Meshery. Learn more at https://docs.meshery.io/concepts/logical/teams
type Team struct {
	// Id A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	Id externalRef0.Uuid `json:"id" yaml:"id"`

	// Name Team name
	Name string `db:"name" json:"name" yaml:"name"`

	// Description Team description
	Description *string `db:"description" json:"description,omitempty" yaml:"description,omitempty"`

	// Owner A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	Owner *externalRef0.Uuid `json:"owner,omitempty" yaml:"owner,omitempty"`

	// Metadata Additional metadata for the team
	Metadata  core.Map          `db:"metadata" json:"metadata,omitempty" yaml:"metadata,omitempty"`
	CreatedAt externalRef0.Time `json:"created_at,omitempty" yaml:"created_at,omitempty"`
	UpdatedAt externalRef0.Time `json:"updated_at,omitempty" yaml:"updated_at,omitempty"`
	DeletedAt externalRef0.Time `json:"deleted_at,omitempty" yaml:"deleted_at,omitempty"`
}

// TeamPage Paginated list of teams
type TeamPage struct {
	Page       externalRef0.Number `json:"page,omitempty" yaml:"page,omitempty"`
	PageSize   externalRef0.Number `json:"page_size,omitempty" yaml:"page_size,omitempty"`
	Teams      []Team              `json:"teams,omitempty" yaml:"teams,omitempty"`
	TotalCount externalRef0.Number `json:"total_count,omitempty" yaml:"total_count,omitempty"`
}

// TeamPayload Payload for creating a new team
type TeamPayload struct {
	Description externalRef0.Text `json:"description,omitempty" yaml:"description,omitempty"`
	Name        externalRef0.Text `json:"name" yaml:"name"`
}

// TeamUpdatePayload Payload for updating an existing team
type TeamUpdatePayload struct {
	Description externalRef0.Text `json:"description,omitempty" yaml:"description,omitempty"`
	Name        externalRef0.Text `json:"name,omitempty" yaml:"name,omitempty"`
}

// TeamsUsersMapping Mapping between teams and users
type TeamsUsersMapping struct {
	CreatedAt externalRef0.Time `json:"created_at,omitempty" yaml:"created_at,omitempty"`

	// DeletedAt SQL null Timestamp to handle null values of time.
	DeletedAt externalRef0.NullTime  `json:"deleted_at,omitempty" yaml:"deleted_at,omitempty"`
	Id        externalRef0.GeneralId `db:"id" json:"id" yaml:"id"`
	TeamId    externalRef0.TeamId    `db:"team_id" json:"team_id" yaml:"team_id"`
	UpdatedAt externalRef0.Time      `json:"updated_at,omitempty" yaml:"updated_at,omitempty"`

	// UserId user's email or username
	UserId externalRef0.UserId `json:"user_id,omitempty" yaml:"user_id,omitempty"`
}

// TeamsUsersMappingPage Paginated list of team-user mappings
type TeamsUsersMappingPage struct {
	Page              externalRef0.Number `json:"page,omitempty" yaml:"page,omitempty"`
	PageSize          externalRef0.Number `json:"page_size,omitempty" yaml:"page_size,omitempty"`
	TeamsUsersMapping []TeamsUsersMapping `json:"teams_users_mapping,omitempty" yaml:"teams_users_mapping,omitempty"`
	TotalCount        externalRef0.Number `json:"total_count,omitempty" yaml:"total_count,omitempty"`
}

// ExternalRef0Order defines model for order.
type ExternalRef0Order = string

// OrgId defines model for orgId.
type OrgId = externalRef0.OrganizationId

// ExternalRef0Page defines model for page.
type ExternalRef0Page = string

// ExternalRef0Pagesize defines model for pagesize.
type ExternalRef0Pagesize = string

// ExternalRef0Search defines model for search.
type ExternalRef0Search = string

// TeamId defines model for teamId.
type TeamId = externalRef0.TeamId
